list: $/plus/socialite/models/followmodel/columns.yaml
modelClass: Plus\Socialite\Models\FollowModel
title: Follow
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'plus/socialite/follow/update/:id'
